version: '3'
services:
  motel-dotnet:
    build: /MotelDotNetCore
    container_name: motel-dotnet
    restart: unless-stopped
    ports:
      - 80
      - 443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80