version: '3'
services:
  motel-dotnet:
    build: ./MotelDotNetCore
    container_name: motel-dotnet
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./contoso.com.crt:/https/server.crt
      - ./contoso.com.key:/https/server.key
      - ./contoso.com.pfx:/https/server.pfx
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/server.pfx